// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxPQ34gGcC8FxGMefSneCkSjgBSSs57I',
    appId: '1:634788140788:web:37085fe2738685a0bbb0a1',
    messagingSenderId: '634788140788',
    projectId: 'sadhanacart-2d590',
    authDomain: 'sadhanacart-2d590.firebaseapp.com',
    storageBucket: 'sadhanacart-2d590.firebasestorage.app',
    measurementId: 'G-8D9ZD02MPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCv40C-owLa3UYgZ9Y8u0n4bLfgyGDqE',
    appId: '1:634788140788:android:3da97f96b3d888e6bbb0a1',
    messagingSenderId: '634788140788',
    projectId: 'sadhanacart-2d590',
    storageBucket: 'sadhanacart-2d590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbWG4_ZawMB5XynaTziir26Y4qEvyLrg',
    appId: '1:634788140788:ios:705d0ddcc86c2e6abbb0a1',
    messagingSenderId: '634788140788',
    projectId: 'sadhanacart-2d590',
    storageBucket: 'sadhanacart-2d590.firebasestorage.app',
    iosBundleId: 'com.example.sadhanacart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbWG4_ZawMB5XynaTziir26Y4qEvyLrg',
    appId: '1:634788140788:ios:705d0ddcc86c2e6abbb0a1',
    messagingSenderId: '634788140788',
    projectId: 'sadhanacart-2d590',
    storageBucket: 'sadhanacart-2d590.firebasestorage.app',
    iosBundleId: 'com.example.sadhanacart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxPQ34gGcC8FxGMefSneCkSjgBSSs57I',
    appId: '1:634788140788:web:214dfd039cb1aa4ebbb0a1',
    messagingSenderId: '634788140788',
    projectId: 'sadhanacart-2d590',
    authDomain: 'sadhanacart-2d590.firebaseapp.com',
    storageBucket: 'sadhanacart-2d590.firebasestorage.app',
    measurementId: 'G-MCKGP3T064',
  );
}
